2020-07-18 19:37:57,331 DEBUG    root            Loaded Command Group: ['gcloud', 'compute']
2020-07-18 19:37:57,564 DEBUG    root            Loaded Command Group: ['gcloud', 'compute', 'ssh']
2020-07-18 19:37:57,569 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [[USER@]INSTANCE: "twitter-hatena"]
2020-07-18 19:37:57,689 DEBUG    root            (gcloud.compute.ssh) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/surface/compute/ssh.py", line 153, in Run
    client = holder.client
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/base_classes.py", line 68, in client
    self._api_version, self._no_http)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 56, in __init__
    self._API_NAME, self._api_version, no_http=no_http)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis.py", line 328, in GetClientInstance
    CheckResponseForApiEnablement())
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/api_lib/util/apis_internal.py", line 167, in _GetClientInstance
    response_encoding=transport.ENCODING)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/credentials/http.py", line 78, in Http
    allow_account_impersonation, use_google_auth)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/credentials/transport.py", line 84, in WrapCredentials
    creds = store.LoadIfEnabled(allow_account_impersonation, use_google_auth)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 489, in LoadIfEnabled
    use_google_auth=use_google_auth)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 586, in Load
    cred = _Load(account, scopes, prevent_refresh, use_google_auth)
  File "/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 668, in _Load
    named_configs.ActiveConfig(False).file_path)
googlecloudsdk.core.credentials.store.NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2020-07-18 19:37:57,691 ERROR    root            (gcloud.compute.ssh) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
